version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command:
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t nodereadblog -t vikas/nodereadblog:latest .
            echo $DOCKER_PASSWORD | docker login -u admin --password-stdin
            docker push vikas/nodereadblog:latest

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - build_docker_image
 fkjfe





# version: 2.1
# jobs:
#    build_test:
#     docker:
#      - image: circleci/node:14
#     steps:
#      - checkout
#      - run:
#        name: Install npm dependencies
#        command:
#          npm install --save 
#   build_docker_image:
#    docker:
#      - image: circleci/node:12
#   steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: false
#      - run:
#          name: Build Docker image
#          command: |
#            docker build -t nodereadblog -t vikas/nodereadblog:latest .
#            echo $DOCKER_PASSWORD | docker login -u admin --password-h3ll0sir
#            docker push vikas/nodereadblog:latest
#   workflows:
#    build_test:
#      jobs:
#        - build_test
#        - build_docker_image