version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    working_directory: ~/read-blog-app
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - restore_cache:
          key: read-blog-appp-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: read-blog-app-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test







# version: 2.1
# jobs:
#   build_test:
#     docker:
#       - image: circleci/node:14
#     steps:
#       - checkout
#       - run:
#           name: Install npm dependencies
#           command:
#             npm install --save

#   build_docker_image:
#     docker:
#       - image: circleci/node:12
#     steps:
#       - checkout
#       - setup_remote_docker:
#           docker_layer_caching: false
#       - run:
#           name: Build Docker image
#           command: |
#             docker build -t nodereadblog -t vikas/nodereadblog:latest .
#             echo $DOCKER_PASSWORD | docker login -u admin --password-stdin
#             docker push vikas/nodereadblog:latest

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build_test
#       - build_docker_image






# version: 2.1
# jobs:
#    build_test:
#     docker:
#      - image: circleci/node:14
#     steps:
#      - checkout
#      - run:
#        name: Install npm dependencies
#        command:
#          npm install --save 
#   build_docker_image:
#    docker:
#      - image: circleci/node:12
#   steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: false
#      - run:
#          name: Build Docker image
#          command: |
#            docker build -t nodereadblog -t vikas/nodereadblog:latest .
#            echo $DOCKER_PASSWORD | docker login -u admin --password-h3ll0sir
#            docker push vikas/nodereadblog:latest
#   workflows:
#    build_test:
#      jobs:
#        - build_test
#        - build_docker_image